#!/usr/bin/env bash
# hooks/post-session.sh
# Installed by install.sh into <repo>/.git/hooks/post-commit
#
# After every commit, checks if a mem-con submodule has changed memory files.
# Reads .memcon-context to know which context area is active.
# Shows the user a diff and asks if they want to open a PR.

set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
MEMCON_SUBMODULE_PATH=""
CONTEXT_FILE=".memcon-context"

# Find the mem-con submodule path in this repo
if [ -f ".gitmodules" ]; then
  MEMCON_SUBMODULE_PATH=$(git config --file .gitmodules --get-regexp 'submodule\..*\.url' 2>/dev/null \
    | grep "mem-con" \
    | head -1 \
    | awk '{print $1}' \
    | sed 's/submodule\.\(.*\)\.url/\1/' || true)
fi

# If not a submodule repo, check if we're directly inside mem-con
if [ -z "$MEMCON_SUBMODULE_PATH" ]; then
  if git remote -v 2>/dev/null | grep -q "mem-con"; then
    MEMCON_SUBMODULE_PATH="."
  fi
fi

# Nothing to do if mem-con isn't in play
if [ -z "$MEMCON_SUBMODULE_PATH" ]; then
  exit 0
fi

# ── Read active context ──────────────────────────────────────────────────────
if [ ! -f "$CONTEXT_FILE" ]; then
  exit 0  # No active context — skip silently
fi

ACTIVE_CONTEXT=$(cat "$CONTEXT_FILE" | tr -d '[:space:]')
if [ -z "$ACTIVE_CONTEXT" ]; then
  exit 0
fi

# ── Guard: never auto-push shared memory ────────────────────────────────────
# memory/shared/ is team-wide context. Users must explicitly run /sync-memory
# to propose changes — it should never happen automatically.
if [ "$ACTIVE_CONTEXT" = "shared" ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  mem-con: shared memory changes detected."
  echo "  Shared memory is NOT auto-submitted — it affects all team members."
  echo "  Run /sync-memory when you are ready to propose these"
  echo "  changes to the team for review."
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  exit 0
fi

# ── Find changed memory files for this context ──────────────────────────────
MEMORY_PATH="${MEMCON_SUBMODULE_PATH}/memory"

# Get files changed in the last commit that belong to this context.
# Explicitly exclude memory/shared/ even if context slug accidentally matches.
CHANGED_FILES=$(git diff HEAD~1 --name-only 2>/dev/null \
  | grep "^${MEMORY_PATH}.*${ACTIVE_CONTEXT}" \
  | grep -v "^${MEMORY_PATH}/shared/" || true)

if [ -z "$CHANGED_FILES" ]; then
  exit 0  # No memory changes for this context
fi

# ── Show diff ───────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  mem-con: context changes detected for [${ACTIVE_CONTEXT}]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
git diff HEAD~1 -- $CHANGED_FILES
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Prompt for PR ────────────────────────────────────────────────────────────
read -r -p "  Submit these context changes as a PR to mem-con? [y/N] " response
if [[ ! "$response" =~ ^[Yy]$ ]]; then
  echo "  Skipped. Run /sync-memory manually when ready."
  exit 0
fi

# ── Create PR ────────────────────────────────────────────────────────────────
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH="context/${ACTIVE_CONTEXT}-${TIMESTAMP}"

# Check if gh CLI is available
if ! command -v gh &>/dev/null; then
  echo "  ERROR: gh CLI not installed. Install from https://cli.github.com and retry."
  exit 1
fi

# If we're in a consuming repo (submodule), cd into the submodule for the PR
ORIGINAL_DIR=$(pwd)
if [ "$MEMCON_SUBMODULE_PATH" != "." ]; then
  cd "$MEMCON_SUBMODULE_PATH"
fi

git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"
git add memory/ 2>/dev/null || true
git commit -m "context(${ACTIVE_CONTEXT}): update memory from session" --allow-empty
git push origin "$BRANCH"

gh pr create \
  --title "context(${ACTIVE_CONTEXT}): update memory from session" \
  --body "$(cat << EOF
## Memory PR — ${ACTIVE_CONTEXT}

Auto-generated by post-session hook after agent session.

**Context:** ${ACTIVE_CONTEXT}
**Session date:** $(date +%Y-%m-%d)

### Changed files:
$(echo "$CHANGED_FILES" | sed 's/^/- /')

### Checklist:
- [ ] Content is accurate and cites sources
- [ ] last_updated date updated
- [ ] No sensitive information included
- [ ] Frontmatter is valid YAML
EOF
)"

echo ""
echo "  PR opened for ${ACTIVE_CONTEXT} memory updates."
echo "    Area contact will review via CODEOWNERS."

cd "$ORIGINAL_DIR"
